## Haytham Elghazel et Orhan Yazar

In [1]:
import numpy as np 
np.set_printoptions(threshold=10000,suppress=True) 
import pandas as pd
import warnings
import matplotlib.pyplot as plt 
warnings.filterwarnings('ignore')

# Partie 1

In [2]:
credit=pd.read_csv('./credit_scoring.csv',sep=";",header=0)

In [3]:
credit.head(3)

Seniority  Home  Time   Age  Marital  Records  Job  Expenses  Income  \
0        9.0   1.0  60.0  30.0      0.0      1.0  1.0      73.0   129.0   
1       17.0   1.0  60.0  58.0      1.0      1.0  0.0      48.0   131.0   
2       10.0   0.0  36.0  46.0      0.0      2.0  1.0      90.0   200.0   

   Assets  Debt  Amount   Price  Status  
0     0.0   0.0   800.0   846.0       1  
1     0.0   0.0  1000.0  1658.0       1  
2  3000.0   0.0  2000.0  2985.0       0

In [ ]:
30 800
30 1000
40 1000

In [4]:
credit.shape

(4375, 14)

In [5]:
X=credit.iloc[:,:13].values
Y=credit.iloc[:,13].values

In [11]:
mp=100*np.sum(Y==0)/len(Y)
bp=100*np.sum(Y==1)/len(Y)

print("% Bon payeurs : {0:.2f} % Mauvais payeurs : {1:.2f}".format(bp,mp))

% Bon payeurs : 72.21 % Mauvais payeurs : 27.79


In [39]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import BaggingClassifier

In [13]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.5,random_state=1)

## Lancement des classifieurs

In [28]:
def classifieurs(Xtrain,Xtest,Ytrain,Ytest):
    DT=DecisionTreeClassifier(criterion='gini',random_state=1) #CART
    DT.fit(Xtrain,Ytrain)
    YDT=DT.predict(Xtest)

    print("Arbre de décision : Accuracy = {0:.2f}".format(accuracy_score(Ytest,YDT)*100))
    print(confusion_matrix(Ytest,YDT))

    print()

    KNN=KNeighborsClassifier(n_neighbors=5) #KNN
    KNN.fit(Xtrain,Ytrain)
    YKNN=KNN.predict(Xtest)

    print("KNN : Accuracy = {0:.2f}".format(accuracy_score(Ytest,YKNN)*100))
    print(confusion_matrix(Ytest,YKNN))

    print()

In [29]:
classifieurs(Xtrain,Xtest,Ytrain,Ytest)

Arbre de décision : Accuracy = 72.71
[[ 325  279]
 [ 318 1266]]

KNN : Accuracy = 72.49
[[ 189  415]
 [ 187 1397]]



### Normalisation des données

In [30]:
SS=StandardScaler()
SS.fit(Xtrain)
Xtrain_norm=SS.transform(Xtrain)
Xtest_norm=SS.transform(Xtest)

classifieurs(Xtrain_norm,Xtest_norm,Ytrain,Ytest)

Arbre de décision : Accuracy = 72.71
[[ 322  282]
 [ 315 1269]]

KNN : Accuracy = 75.27
[[ 286  318]
 [ 223 1361]]



### Ajout des variables

In [38]:
pca=PCA(n_components=3)
pca.fit(Xtrain_norm)
Xtrain_pca=np.concatenate((Xtrain_norm,pca.transform(Xtrain_norm)),axis=1)
Xtest_pca=np.concatenate((Xtest_norm,pca.transform(Xtest_norm)),axis=1)

classifieurs(Xtrain_pca,Xtest_pca,Ytrain,Ytest)


Arbre de décision : Accuracy = 73.63
[[ 351  253]
 [ 324 1260]]

KNN : Accuracy = 75.64
[[ 283  321]
 [ 212 1372]]



In [41]:
BAG=BaggingClassifier(n_estimators=100,random_state=1) #BAG
BAG.fit(Xtrain,Ytrain)
YBAG=BAG.predict(Xtest)
print("Bagging : Accuracy = {0:.2f}".format(accuracy_score(Ytest,YBAG)*100))
print(confusion_matrix(Ytest,YBAG))

Bagging : Accuracy = 78.29
[[ 330  274]
 [ 201 1383]]
